### ISSUE TITLE
Frontpage: Shop by brand + Category texts

### ISSUE THREAD

**Issue by ahmikkelsen** [jackjonesfashion/JJ-CSS#115]
Hi,

Can you please add in the "Shop by brand" line above the brand boxes, and update the "Categories" texts to the ones in this document?
https://www.dropbox.com/s/hf9uxt8ve64obun/frontpage-texts.xlsx?dl=0

**Comment by jeppeolesen** [comment]
E-com fixed the first issue by breaking something else. We're still waiting for this to be resolved so we can add it.

**Comment by jeppeolesen** [comment]
No longer relevant, as we're getting a new storefront
