### ISSUE TITLE
Frontpage: Highlights area: Mellemrum mellem tekst er forskellig

### ISSUE THREAD

**Issue by ahmikkelsen** [jackjonesfashion/JJ-CSS#116]
De bliver distribueret lidt random!

![screenshot 2014-12-08 13 48 32](https://cloud.githubusercontent.com/assets/6907325/5339423/08c1ccdc-7ee1-11e4-9bb5-e2ee317b2345.png)
![screenshot 2014-12-08 13 48 35](https://cloud.githubusercontent.com/assets/6907325/5339424/08c22ec0-7ee1-11e4-90fc-9414a6cafae8.png)
![screenshot 2014-12-08 13 48 38](https://cloud.githubusercontent.com/assets/6907325/5339425/08c2c5e2-7ee1-11e4-9efa-8f8b6eb3b952.png)

**Comment by jeppeolesen** [comment]
No longer relevant as we're developing a new storefront
