### ISSUE TITLE
Navigation: Brand logo clickable to go to the Brand homepage

### ISSUE THREAD

**Issue by ahmikkelsen** [jackjonesfashion/JJ-CSS#123]
Currently it's not a link.

![image](https://cloud.githubusercontent.com/assets/6907325/6458575/5ef490c6-c185-11e4-8751-57f0f92ba2ac.png)

**Comment by jeppeolesen** [comment]
Please create this in our new task management repo: https://github.com/jackjonesfashion/tasks/issues
