### ISSUE TITLE
Frontpage: Highlights area skifter højde før nødvendigt

### ISSUE THREAD

**Issue by ahmikkelsen** [jackjonesfashion/JJ-CSS#98]
Når vi f.eks. kun har 4 punkter laver den stadigvæk plads som om der er 2 rows før det rent faktisk er nødvendigt: https://www.dropbox.com/s/yjcke1fv61y4w9r/Screenshot%202014-11-17%2015.11.24.png?dl=0

**Comment by jeppeolesen** [comment]
No longer relevant as we're developing a new storefront
